version: '3.6'
services:

  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    container_name: graphql-engine
    build: ./custom
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always

volumes:
  db_data:

