FROM hasura/graphql-engine:v2.2.0

WORKDIR /app

ENV HASURA_GRAPHQL_ENABLE_CONSOLE="true" \
    HASURA_GRAPHQL_DEV_MODE="true" \
    HASURA_GRAPHQL_ENABLED_LOG_TYPES="startup, http-log, webhook-log, websocket-log, query-log" \
    HASURA_GRAPHQL_METADATA_DATABASE_URL="postgres://postgres:postgrespassword@postgres:5432/postgres" \
    PG_DATABASE_URL="postgres://postgres:postgrespassword@postgres:5432/postgres"
    # HASURA_GRAPHQL_ADMIN_SECRET="myadminsecretkey"

EXPOSE 80
